[package]
name = "lightwell-s0-probes"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
moxcms = { version = "=0.7.11", default-features = false }
image = { version = "=0.25.9", default-features = false, features = ["jpeg", "png"] }
iced = { optional = true, version = "=0.14.0", default-features = false, features = ["wgpu", "image-without-codecs", "sysinfo", "tokio", "x11", "wayland"] }
eframe = { optional = true, version = "=0.33.3", default-features = false, features = ["wgpu", "default_fonts", "x11", "wayland"] }
rfd = { optional = true, version = "=0.15.4", default-features = false, features = ["xdg-portal", "async-std"] }
serde_json = "=1.0.149"

[lints.rust]
unsafe_code = "forbid"

[features]
iced-ui = ["dep:iced", "dep:rfd"]
egui-ui = ["dep:eframe", "dep:rfd"]

[[bin]]
name = "iced-viewer"
required-features = ["iced-ui"]

[[bin]]
name = "egui-viewer"
required-features = ["egui-ui"]
